name: Publish to Exchange & Deploy to CH2.0

on:
  push:
    branches: [ develop ]
    
jobs:         
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 8
  
  deploy-sanbox:
    needs: build    
    runs-on: ubuntu-latest
    environment:
      name: SANDBOX
    if: github.ref == 'refs/heads/develop'
    steps: 
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 8
          
      - name: Publish to Exchange
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"
      - name: Deploy to CloudHub 2.0
        run: |
          mvn clean deploy --settings .maven/settings.xml -DmuleDeploy -DskipMunitTests \
          -Dmule.env="Sandbox" \
          -DappName="${{vars.APPNAME}}-dev" \
          -Dclient.id="${{secrets.CONNECTED_APP_CLIENT_ID}}" \
          -Dclient.secret="${{secrets.CONNECTED_APP_CLIENT_SECRET}}" 

  deploy-sit:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: SIT
    if: ${{ github.ref == 'refs/heads/sit' && github.event.pull_request.merged == true }}
    steps:
      - name: Publish to Exchange
        run: |
          mvn clean deploy --settings .maven/settings.xml \
          -Dmule.env="SIT" \
          -Dclient.id="${{secrets.CONNECTED_APP_CLIENT_ID}}" \
          -Dclient.secret="${{secrets.CONNECTED_APP_CLIENT_SECRET}}" \
          -Dnexus.username="${{secrets.NEXUS_USERNAME_NON_PROD}}" \
          -Dnexus.password="${{secrets.NEXUS_PASSWORD_NON_PROD}}" \
          -Dvault.key="${{secrets.VAULT_KEY_NON_PROD}}"

      - name: Deploy to CloudHub 2.0
        run: |
          mvn clean deploy --settings .maven/settings.xml -DmuleDeploy -DskipMunitTests \
          -Dmule.env="SIT" \
          -DappName="${{vars.APPNAME}}-sit" \
          -Dclient.id="${{secrets.CONNECTED_APP_CLIENT_ID}}" \
          -Dclient.secret="${{secrets.CONNECTED_APP_CLIENT_SECRET}}" \
          -Dvault.key="${{secrets.VAULT_KEY_NON_PROD}}" \
          -Danypoint.platform.client_id="${{secrets.AP_CLIENT_ID_NON_PROD}}" \
          -Danypoint.platform.client_secret="${{secrets.AP_CLIENT_SECRET_NON_PROD}}" \
          -Dnexus.username="${{secrets.NEXUS_USERNAME_NON_PROD}}" \
          -Dnexus.password="${{secrets.NEXUS_PASSWORD_NON_PROD}}"
